### PR TITLE
Fix licence issues failing to insert for review

### PR DESCRIPTION
**Pull request by Cruikshanks**
https://eaflood.atlassian.net/browse/WATER-4375

In recent testing of triggering an SROC two-part tariff bill run, we've seen errors thrown by the `PersistAllocatedLicenceToResultsService`.

After investigating it is not the issue. It was being asked to persist every issue for every element and return found by `DetermineLicenceIssuesService` in its `issues` field.

No de-duping of the issues is taking place so it's blowing past the 255-char limit for the DB field for some licences.

This causes the bill run to fail and the system app to crash (but we'll deal with that in another fix!)

This change will de-dupe the issues found _before_ they are persisted to keep us under the 255 char limit.

### CODE REVIEW

**Review by Beckyrose200 — APPROVED** [review]

**Review by Beckyrose200 — CHANGES_REQUESTED** [review]
If the maximum the issues string can be in the DB is all the issues once then the string would look like this 

'Abstraction outside period, Aggregate, Checking query, No returns received, Over abstraction, Overlap of charge dates, Returns received but not processed, Returns received late, Return split over charge references, Some returns not received, Unable to match return'

This still surpasses the 255 character limit on the db, so I think we need to change that to be bigger or drop it completely?

**Comment by Jozzey** [comment]
> If the maximum the issues string can be in the DB is all the issues once then the string would look like this
> 
> 'Abstraction outside period, Aggregate, Checking query, No returns received, Over abstraction, Overlap of charge dates, Returns received but not processed, Returns received late, Return split over charge references, Some returns not received, Unable to match return'
> 
> This still surpasses the 255 character limit on the db, so I think we need to change that to be bigger or drop it completely?

I think we should just drop the constraints on these `varchar` columns. They were added unintentionally and if you look at the rest of the DB there are no such constraints on any of the other `varchar` columns (not that I've checked them all).

**Review by Jozzey — APPROVED** [review]

**Review by Beckyrose200 — APPROVED** [review]

**Pull request merged**
