### PR TITLE
Fix region seeder name

### PR DESCRIPTION
**Pull request by jonathangoulding**
A naught fella has been left in the code. This should be removed

### CODE REVIEW

**Comment by Cruikshanks** [comment]
Unless it is urgent, this was spotted and will be resolved by https://github.com/DEFRA/water-abstraction-system/pull/1230

**Comment by jonathangoulding** [comment]
> Unless it is urgent, this was spotted and will be resolved by #1230

This should be breaking tests - but i think they are testing the display name and not the name. So maybe not urgent if the next work is going in.

**Review by Beckyrose200 — COMMENTED** [review]
Can we change it for the test region, so it sets the `isTest` column to true? The tear-down service for the acceptance tests utilises the test region `isTest` property to know what data to delete and with the seeder test region the tear-down is breaking

**Comment by jonathangoulding** [comment]
> Can we change it for the test region, so it sets the `isTest` column to true? The tear-down service for the acceptance tests utilises the test region `isTest` property to know what data to delete and with the seeder test region the tear-down is breaking

You would need to update the data file and columns. Maybe set the default to false allow the data file to override. Might be worth a check on the PR mentioned if that's considered this.

**Comment by Cruikshanks** [comment]
Parking this as we have https://github.com/DEFRA/water-abstraction-system/pull/1230 incoming.

It also deals with @Beckyrose200 question about flagging the region as `is_test`.

**Comment by Cruikshanks** [comment]
Closing as covered by #1230

**Pull request closed without merging**
